name: Deploy pip-agent to Digital Ocean

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Deploy code to Digital Ocean Droplet
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: |
        echo "$ENV_FILE" > .env
        scp .env root@${{ secrets.DROPLET_IP }}:/var/www/pip-agent/.env
        ssh root@${{ secrets.DROPLET_IP }} << 'EOF'
        sudo apt update
        sudo apt install -y python3 python3-venv python3-pip pipx
        export PATH=$PATH:/root/.local/bin
        cd /var/www/pip-agent
        git pull origin main
        rm -rf venv
        python3 -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
        systemctl restart pip-agent
        # Health check
        sleep 10
        if curl -f http://localhost:5000; then
          echo "Deployment successful"
        else
          echo "Deployment failed"
          exit 1
        fi
        EOF